/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Pacientes;

import Vistas.General;
import com.mycompany.practicaunoarchivos.Models.Patient;
import com.mycompany.practicaunoarchivos.ServicePatients.DeletePatient;
import com.mycompany.practicaunoarchivos.ServicePatients.ListPatients;
import com.mycompany.practicaunoarchivos.ServicePatients.SearchPatient;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class GeneralPatient extends javax.swing.JFrame {

    /**
     * Creates new form GeneralPatient
     */
    public GeneralPatient() {
        initComponents();

        getContentPane().setBackground(
                new java.awt.Color(235, 225, 245)
        );

        jPanel1.setBackground(
                new java.awt.Color(245, 238, 250)
        );

        jTable1.setRowHeight(28);

        jTable1.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)
        );

        jTable1.setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12)
        );

    }

    private void llenarTabla(ArrayList<Patient> pacientes) {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("INE");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nacimiento");
        modelo.addColumn("Genero");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Tipo Sangre");

        for (Patient patient : pacientes) {
            modelo.addRow(new Object[]{
                patient.getIne(),
                patient.getFullName(),
                patient.getBirthdate(),
                patient.getGender(),
                patient.getPhoneNumber(),
                patient.getEmail(),
                patient.getBloodType()
            });
        }

        jTable1.setModel(modelo);
        jTable1.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        BotonTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        crearpacienteboton = new javax.swing.JButton();
        modificarpacienteboton = new javax.swing.JButton();
        eliminarboton = new javax.swing.JButton();
        cerrarboton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Buscar paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        BotonTodos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonTodos.setText("Listar Todos");
        BotonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTodosActionPerformed(evt);
            }
        });
        jPanel1.add(BotonTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "INE", "Nombre", "Fecha Nacimiento", "Genero", "Telefono", "Email", "Tipo de sangre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 170));

        crearpacienteboton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crearpacienteboton.setText("Crear paciente");
        crearpacienteboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearpacientebotonActionPerformed(evt);
            }
        });
        jPanel1.add(crearpacienteboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        modificarpacienteboton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarpacienteboton.setText("Modificar paciente");
        modificarpacienteboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarpacientebotonActionPerformed(evt);
            }
        });
        jPanel1.add(modificarpacienteboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        eliminarboton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarboton.setText("Eliminar Paciente");
        eliminarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbotonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        cerrarboton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cerrarboton.setText("Cerrar");
        cerrarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarbotonActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void BotonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTodosActionPerformed
        // TODO add your handling code here:
        ListPatients lista = new ListPatients();

        ArrayList<Patient> pacientes = lista.listPatients();

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        for (Patient patient : pacientes) {

            modelo.addRow(new Object[]{
                patient.getIne(),
                patient.getFullName(),
                patient.getBirthdate(),
                patient.getGender(),
                patient.getPhoneNumber(),
                patient.getEmail(),
                patient.getBloodType()
            });
        }
    }//GEN-LAST:event_BotonTodosActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        String buscar = txtSearch.getText().trim();

        if (buscar.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un INE, nombre o apellido para buscar.");
            return;
        }

        SearchPatient searchPatient = new SearchPatient();

        ArrayList<Patient> resultados = searchPatient.searchPatient(buscar);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Patient patient : resultados) {

            modelo.addRow(new Object[]{
                patient.getIne(),
                patient.getFullName(),
                patient.getBirthdate(),
                patient.getGender(),
                patient.getPhoneNumber(),
                patient.getEmail(),
                patient.getBloodType()
            });
        }

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró ningún paciente.");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void crearpacientebotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearpacientebotonActionPerformed
        // TODO add your handling code here:
        ViewCreatePatient view = new ViewCreatePatient();
        view.setVisible(true);
    }//GEN-LAST:event_crearpacientebotonActionPerformed

    private void modificarpacientebotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarpacientebotonActionPerformed
        // TODO add your handling code here:
        ViewUpdatePatient viewupdate = new ViewUpdatePatient();
        viewupdate.setVisible(true);
    }//GEN-LAST:event_modificarpacientebotonActionPerformed

    private void cerrarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarbotonActionPerformed
        // TODO add your handling code here:
         General vista = new General();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarbotonActionPerformed

    private void eliminarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbotonActionPerformed
        // TODO add your handling code here:
        String textoIne = txtSearch.getText().trim();

        if (textoIne.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el INE del paciente que desea eliminar.");
            return;
        }

        try {
            int ine = Integer.parseInt(textoIne);

            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro que desea eliminar este paciente?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (respuesta != JOptionPane.YES_OPTION) {
                return;
            }

            DeletePatient eliminar = new DeletePatient();
            boolean resultado = eliminar.deletePatient(ine);

            if (resultado) {
                JOptionPane.showMessageDialog(this, "Paciente eliminado correctamente.");
                txtSearch.setText("");
                BotonTodosActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un paciente con ese INE o ya fue eliminado.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El INE debe ser un número entero válido.");
        }
    }//GEN-LAST:event_eliminarbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTodos;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton cerrarboton;
    private javax.swing.JButton crearpacienteboton;
    private javax.swing.JButton eliminarboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarpacienteboton;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
