/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Pacientes;

import com.mycompany.practicaunoarchivos.Models.Patient;
import com.mycompany.practicaunoarchivos.ServicePatients.ListPatients;
import com.mycompany.practicaunoarchivos.ServicePatients.UpdatePatient;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class ViewUpdatePatient extends javax.swing.JFrame {

    /**
     * Creates new form ViewUpdatePatient
     */
    public ViewUpdatePatient() {
        initComponents();
    }
    private Patient pacienteEncontrado;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbFullName = new javax.swing.JLabel();
        txtIne = new javax.swing.JTextField();
        lbFullName1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lbFullName2 = new javax.swing.JLabel();
        lbFullName3 = new javax.swing.JLabel();
        txtgenero = new javax.swing.JTextField();
        lbFullName4 = new javax.swing.JLabel();
        lbFullName5 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        lbFullName6 = new javax.swing.JLabel();
        txttipoSangre = new javax.swing.JTextField();
        txtnacimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFullName.setText("INE");
        jPanel1.add(lbFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 196, -1));

        txtIne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIneActionPerformed(evt);
            }
        });
        jPanel1.add(txtIne, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, -1));

        lbFullName1.setText("Nombre y Apellido ( obligatorio)");
        jPanel1.add(lbFullName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 196, -1));

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, -1));

        lbFullName2.setText("FECHA DE NACIMIENTO");
        jPanel1.add(lbFullName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 196, -1));

        lbFullName3.setText("GENERO");
        jPanel1.add(lbFullName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 196, -1));

        txtgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        lbFullName4.setText("TELEFONO");
        jPanel1.add(lbFullName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 196, -1));

        lbFullName5.setText("EMAIL");
        jPanel1.add(lbFullName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 196, -1));

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 150, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, -1));

        lbFullName6.setText("TIPO DE SANGRE");
        jPanel1.add(lbFullName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 196, -1));

        txttipoSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoSangreActionPerformed(evt);
            }
        });
        jPanel1.add(txttipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, -1));

        txtnacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("BUSCAR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 70, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 200, -1));

        ButtonBuscar.setText("BUSCAR");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 100, 50));

        jButton3.setText("GUARDAR CAMBIOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 50));

        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 130, 50));

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIneActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeneroActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoSangreActionPerformed

    private void txtnacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnacimientoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // TODO add your handling code here:
        try {
            int ineBuscado = Integer.parseInt(txtSearch.getText().trim());

            for (Patient patient : new ListPatients().listPatients()) {
                if (patient.getIne() == ineBuscado) {

                    pacienteEncontrado = patient;

                    txtIne.setText(String.valueOf(patient.getIne()));
                    txtFullName.setText(patient.getFullName());
                    txtnacimiento.setText(patient.getBirthdate().toString());
                    txtgenero.setText(patient.getGender());
                    txtnumero.setText(patient.getPhoneNumber());
                    txtemail.setText(patient.getEmail());
                    txttipoSangre.setText(patient.getBloodType());

                    txtIne.setEditable(false);

                    JOptionPane.showMessageDialog(this, "Paciente encontrado.");
                    return;
                }
            }

            JOptionPane.showMessageDialog(this, "No existe un paciente con ese INE.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa un INE numérico.");
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (pacienteEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Primero busca un paciente.");
            return;
        }

        try {
            String nombre = txtFullName.getText().trim();
            java.time.LocalDate fecha = java.time.LocalDate.parse(txtnacimiento.getText().trim());
            String genero = txtgenero.getText().trim();
            String telefono = txtnumero.getText().trim();
            String email = txtemail.getText().trim();
            String tipoSangre = txttipoSangre.getText().trim();

            Patient pacienteActualizado = new Patient(
                    pacienteEncontrado.getIne(), 
                    nombre, fecha, genero, telefono, email, tipoSangre, false
            );

           UpdatePatient updater  = new UpdatePatient();

            boolean actualizado = updater.update(pacienteActualizado);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Paciente actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Revisa los datos. Fecha formato yyyy-MM-dd.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GeneralPatient vista = new GeneralPatient();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GeneralPatient vista = new GeneralPatient();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbFullName1;
    private javax.swing.JLabel lbFullName2;
    private javax.swing.JLabel lbFullName3;
    private javax.swing.JLabel lbFullName4;
    private javax.swing.JLabel lbFullName5;
    private javax.swing.JLabel lbFullName6;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIne;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnacimiento;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txttipoSangre;
    // End of variables declaration//GEN-END:variables
}
