/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Pacientes;

import com.mycompany.practicaunoarchivos.DoctorService.CreateDoctor;
import com.mycompany.practicaunoarchivos.Models.Doctor;
import com.mycompany.practicaunoarchivos.Models.Patient;
import com.mycompany.practicaunoarchivos.ServicePatients.CreatePatient;
import com.mycompany.practicaunoarchivos.ServicePatients.ListPatients;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class ViewCreatePatient extends javax.swing.JFrame {

    /**
     * Creates new form ViewCreatePatient
     */
    private void limpiarCampos() {
        txtIne.setText("");
        txtFullName.setText("");
        txtnacimiento.setText("");
        txtgenero.setText("");
        txtnumero.setText("");
        txtemail.setText("");
        txttipoSangre.setText("");

        txtIne.requestFocus();
    }

    public ViewCreatePatient() {
        initComponents();
        getContentPane().setBackground(new Color(235, 225, 245));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbFullName = new javax.swing.JLabel();
        txtIne = new javax.swing.JTextField();
        lbFullName1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lbFullName2 = new javax.swing.JLabel();
        txtnacimiento = new javax.swing.JTextField();
        lbFullName3 = new javax.swing.JLabel();
        txtgenero = new javax.swing.JTextField();
        lbFullName4 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        lbFullName5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lbFullName6 = new javax.swing.JLabel();
        txttipoSangre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFullName.setText("INE");
        jPanel1.add(lbFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 196, -1));

        txtIne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIneActionPerformed(evt);
            }
        });
        jPanel1.add(txtIne, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 301, -1));

        lbFullName1.setText("Nombre y Apellido ( obligatorio)");
        jPanel1.add(lbFullName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 196, -1));

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 301, -1));

        lbFullName2.setText("FECHA DE NACIMIENTO");
        jPanel1.add(lbFullName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 196, -1));

        txtnacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 301, -1));

        lbFullName3.setText("GENERO");
        jPanel1.add(lbFullName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 196, -1));

        txtgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 301, -1));

        lbFullName4.setText("TELEFONO");
        jPanel1.add(lbFullName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 196, -1));

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 301, -1));

        lbFullName5.setText("EMAIL");
        jPanel1.add(lbFullName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 196, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 301, -1));

        lbFullName6.setText("TIPO DE SANGRE");
        jPanel1.add(lbFullName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 196, -1));

        txttipoSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoSangreActionPerformed(evt);
            }
        });
        jPanel1.add(txttipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 301, -1));

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIneActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtnacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnacimientoActionPerformed

    private void txtgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeneroActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoSangreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int ine = Integer.parseInt(txtIne.getText().trim());

            ListPatients lista = new ListPatients();

            for (Patient paciente : lista.listPatients()) {
                if (paciente.getIne() == ine) {
                    JOptionPane.showMessageDialog(this, "Ya existe un paciente con este INE.");
                    return;
                }
            }

            String nombre = txtFullName.getText().trim();
            LocalDate fechaNacimiento = LocalDate.parse(txtnacimiento.getText().trim());
            String genero = txtgenero.getText().trim();
            String telefono = txtnumero.getText().trim();
            String email = txtemail.getText().trim();
            String tipoSangre = txttipoSangre.getText().trim();

            if (nombre.isEmpty() || genero.isEmpty()
                    || telefono.isEmpty()
                    || email.isEmpty()
                    || tipoSangre.isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Completa todos los campos.");
                return;
            }

            Patient nuevoPaciente = new Patient(ine, nombre, fechaNacimiento, genero, telefono, email, tipoSangre, false);

            CreatePatient crear = new CreatePatient();
            crear.createPatient(nuevoPaciente);

            JOptionPane.showMessageDialog(this, "Paciente guardado.");

            limpiarCampos();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "El INE debe ser un número.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Fecha inválida. Usa formato: yyyy-MM-dd");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GeneralPatient vistaPat = new GeneralPatient();
        vistaPat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCreatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCreatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCreatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCreatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCreatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbFullName1;
    private javax.swing.JLabel lbFullName2;
    private javax.swing.JLabel lbFullName3;
    private javax.swing.JLabel lbFullName4;
    private javax.swing.JLabel lbFullName5;
    private javax.swing.JLabel lbFullName6;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIne;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnacimiento;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txttipoSangre;
    // End of variables declaration//GEN-END:variables
}
