/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Citas;

import com.mycompany.practicaunoarchivos.Models.Appointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.CancelAppointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.DeleteAppointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.ListAppointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.SearchAppointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.UpdateAppointment;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class GeneralAppointment extends javax.swing.JFrame {

    /**
     * Creates new form GeneralCita
     */
    private final SearchAppointment searchAppointment = new SearchAppointment();
    private final ListAppointment listAppointment = new ListAppointment();
    private final DeleteAppointment deleteAppointment = new DeleteAppointment();

    private String obtenerUuidSeleccionado() {

        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una cita de la tabla."
            );
            return null;
        }

        return jTable1.getValueAt(fila, 0).toString();
    }

    private void cargarTabla(ArrayList<Appointment> appointments) {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("UUID");
        model.addColumn("Paciente");
        model.addColumn("Médico");
        model.addColumn("Fecha");
        model.addColumn("Hora");
        model.addColumn("Motivo");
        model.addColumn("Estado");
        model.addColumn("Observación");

        for (Appointment appointment : appointments) {

            model.addRow(new Object[]{
                appointment.getId(),
                appointment.getInePaciente(),
                appointment.getUUIdDoctor(),
                appointment.getDate(),
                appointment.getStartHour(),
                appointment.getReason(),
                appointment.isStatus(),
                appointment.getObservation()
            });
        }

        jTable1.setModel(model);
    }

    private void mostrarCitas(ArrayList<Appointment> citas) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Appointment cita : citas) {
            modelo.addRow(new Object[]{
                cita.getId(),
                cita.getInePaciente(),
                cita.getUUIdDoctor(),
                cita.getDate(),
                cita.getStartHour(),
                cita.getReason(),
                cita.isStatus(),
                cita.getObservation()
            });
        }
    }

    private void cargarCitas() {
        ListAppointment lista
                = new ListAppointment();

        mostrarCitas(lista.listAppointments());
    }

    public GeneralAppointment() {
        initComponents();
        cargarCitas();

        getContentPane().setBackground(new java.awt.Color(235, 225, 245));
        jPanel1.setBackground(new java.awt.Color(245, 238, 250));

        // Altura de las filas
        jTable1.setRowHeight(32);

       
        jTable1.getTableHeader().setBackground(
                new java.awt.Color(210, 190, 230)
        );
        jTable1.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)
        );

        
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

       
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(180); 
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(180); 
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100); 
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);  
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(180); 
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(250); 
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(100); 

        // Para poder ver las columnas que quedan fuera de la pantalla
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        setSize(1100, 520);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuuid = new javax.swing.JTextField();
        jButtonBuscarUIID = new javax.swing.JButton();
        buttonListadoCita = new javax.swing.JButton();
        ButtonCitaPaciente = new javax.swing.JButton();
        jButtonCitaMedico = new javax.swing.JButton();
        jButtonCitaFecha = new javax.swing.JButton();
        jButtonCitaEstado = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtoncancelarcita = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtoneliminarcita = new javax.swing.JButton();
        Buttonmarcarcita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtoncerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar cita");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(txtuuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, -1));

        jButtonBuscarUIID.setText("Buscar UUID");
        jButtonBuscarUIID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUIIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarUIID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        buttonListadoCita.setText("Listado de cita");
        buttonListadoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListadoCitaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonListadoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        ButtonCitaPaciente.setText("Cita por paciente");
        ButtonCitaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCitaPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCitaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jButtonCitaMedico.setText("Cita por medio");
        jButtonCitaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitaMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCitaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jButtonCitaFecha.setText("Cita por fecha");
        jButtonCitaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitaFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCitaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jButtonCitaEstado.setText("Cita por estado");
        jButtonCitaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitaEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCitaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jButton6.setText("Crear cita");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jButtoncancelarcita.setText("Cancelar Cita");
        jButtoncancelarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoncancelarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jButtonModificar.setText("Modificar observaciones y motivos");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jButtoneliminarcita.setText("Eliminar cita");
        jButtoneliminarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoneliminarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        Buttonmarcarcita.setText("Marcar atendido");
        Buttonmarcarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonmarcarcitaActionPerformed(evt);
            }
        });
        jPanel1.add(Buttonmarcarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UUID citas", "Ine Paciente", "UUID medico", "Fecha", "Hora", "Motivo", "Estado", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 660, 200));

        jButtoncerrar.setText("Cerrar");
        jButtoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonListadoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListadoCitaActionPerformed
        // TODO add your handling code here:
        ArrayList<Appointment> appointments = listAppointment.listAppointments();

        cargarTabla(appointments);
    }//GEN-LAST:event_buttonListadoCitaActionPerformed

    private void ButtonCitaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCitaPacienteActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(this, "Ingrese el INE del paciente:");

        if (texto == null || texto.trim().isEmpty()) {
            return;
        }

        try {
            int ine = Integer.parseInt(texto.trim());
            ArrayList<Appointment> resultado = new ArrayList<>();
            ListAppointment lista = new ListAppointment();

            for (Appointment cita : lista.listAppointments()) {
                if (cita.getInePaciente() == ine) {
                    resultado.add(cita);
                }
            }

            mostrarCitas(resultado);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El INE debe ser numérico.");
        }
    }//GEN-LAST:event_ButtonCitaPacienteActionPerformed

    private void jButtonCitaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitaMedicoActionPerformed
        // TODO add your handling code here:
        String uuid = JOptionPane.showInputDialog(this, "Ingrese el UUID del médico:");

        if (uuid == null || uuid.trim().isEmpty()) {
            return;
        }

        ArrayList<Appointment> resultado = new ArrayList<>();
        ListAppointment lista = new ListAppointment();

        for (Appointment cita : lista.listAppointments()) {
            if (cita.getUUIdDoctor().equalsIgnoreCase(uuid.trim())) {
                resultado.add(cita);
            }
        }

        mostrarCitas(resultado);
    }//GEN-LAST:event_jButtonCitaMedicoActionPerformed

    private void jButtonCitaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitaFechaActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(this, "Ingrese la fecha (YYYY-MM-DD):");

        if (texto == null || texto.trim().isEmpty()) {
            return;
        }

        try {
            java.time.LocalDate fecha = java.time.LocalDate.parse(texto.trim());
            ArrayList<Appointment> resultado = new ArrayList<>();
            ListAppointment lista = new ListAppointment();

            for (Appointment cita : lista.listAppointments()) {
                if (cita.getDate().equals(fecha)) {
                    resultado.add(cita);
                }
            }

            mostrarCitas(resultado);

        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener formato YYYY-MM-DD.");
        }
    }//GEN-LAST:event_jButtonCitaFechaActionPerformed

    private void jButtonCitaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitaEstadoActionPerformed
        // TODO add your handling code here:
        String[] estados = {"programada", "atendida", "cancelada"};

        String estado = (String) JOptionPane.showInputDialog(this, "Seleccione el estado:", "Buscar por estado", JOptionPane.QUESTION_MESSAGE, null, estados, estados[0]);

        if (estado == null) {
            return;
        }

        ArrayList<Appointment> resultado = new ArrayList<>();
        ListAppointment lista = new ListAppointment();

        for (Appointment cita : lista.listAppointments()) {
            if (cita.isStatus().equalsIgnoreCase(estado)) {
                resultado.add(cita);
            }
        }

        mostrarCitas(resultado);
    }//GEN-LAST:event_jButtonCitaEstadoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ViewCreateAppointment viewappoi = new ViewCreateAppointment();
        viewappoi.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtoncancelarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarcitaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        int confirmar = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar esta cita?", "Confirmar cancelación", JOptionPane.YES_NO_OPTION);

        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }

        CancelAppointment cancelar = new CancelAppointment();

        if (cancelar.cancelAppointment(id)) {
            JOptionPane.showMessageDialog(this, "Cita cancelada correctamente.");
            cargarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cancelar la cita.");
        }
    }//GEN-LAST:event_jButtoncancelarcitaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita de la tabla.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();
        String motivoActual = jTable1.getValueAt(fila, 5).toString();
        String observacionActual = jTable1.getValueAt(fila, 7).toString();

        String nuevoMotivo = JOptionPane.showInputDialog(this, "Nuevo motivo:", motivoActual);

        if (nuevoMotivo == null || nuevoMotivo.trim().isEmpty()) {
            return;
        }

        String nuevasObservaciones = JOptionPane.showInputDialog(this, "Nuevas observaciones:", observacionActual);

        if (nuevasObservaciones == null) {
            return;
        }

        UpdateAppointment update = new UpdateAppointment();
        boolean actualizado = update.updateAppointment(id, nuevoMotivo.trim(), nuevasObservaciones.trim());

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Cita modificada correctamente.");
            cargarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo modificar la cita.");
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtoneliminarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarcitaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar esta cita?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmar != JOptionPane.YES_OPTION) {
            return;
        }

        DeleteAppointment eliminar = new DeleteAppointment();

        if (eliminar.deleteAppointment(id)) {
            JOptionPane.showMessageDialog(this, "Cita eliminada correctamente.");
            cargarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar la cita.");
        }
    }//GEN-LAST:event_jButtoneliminarcitaActionPerformed

    private void ButtonmarcarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonmarcarcitaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una cita.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();
        UpdateAppointment update = new UpdateAppointment();

        if (update.markAsAttended(id)) {
            JOptionPane.showMessageDialog(this, "Cita marcada como atendida.");
            cargarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la cita.");
        }
    }//GEN-LAST:event_ButtonmarcarcitaActionPerformed

    private void jButtoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtoncerrarActionPerformed

    private void jButtonBuscarUIIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUIIDActionPerformed
        // TODO add your handling code here:
        String uuid = txtuuid.getText().trim();

        if (uuid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe el UUID de la cita.");
            return;
        }

        SearchAppointment search = new SearchAppointment();
        Appointment cita = search.searchById(uuid);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        if (cita != null) {
            modelo.addRow(new Object[]{
                cita.getId(),
                cita.getInePaciente(),
                cita.getUUIdDoctor(),
                cita.getDate(),
                cita.getStartHour(),
                cita.getReason(),
                cita.isStatus(),
                cita.getObservation()
            });
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la cita.");
        }
    }//GEN-LAST:event_jButtonBuscarUIIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCitaPaciente;
    private javax.swing.JButton Buttonmarcarcita;
    private javax.swing.JButton buttonListadoCita;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonBuscarUIID;
    private javax.swing.JButton jButtonCitaEstado;
    private javax.swing.JButton jButtonCitaFecha;
    private javax.swing.JButton jButtonCitaMedico;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtoncancelarcita;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JButton jButtoneliminarcita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtuuid;
    // End of variables declaration//GEN-END:variables
}
