/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Citas;

import com.mycompany.practicaunoarchivos.DoctorService.ListDoctors;
import com.mycompany.practicaunoarchivos.Models.Appointment;
import com.mycompany.practicaunoarchivos.Models.Doctor;
import com.mycompany.practicaunoarchivos.Models.Patient;
import com.mycompany.practicaunoarchivos.ServiceAppointment.CreateAppointment;
import com.mycompany.practicaunoarchivos.ServiceAppointment.ListAppointment;
import com.mycompany.practicaunoarchivos.ServicePatients.ListPatients;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class ViewCreateAppointment extends javax.swing.JFrame {

    private ArrayList<Doctor> doctoresDisponibles;

    /**
     * Creates new form ViewCreateAppointment
     */
    private void cargarMedicos() {
        try {
            ListDoctors listaDoctores = new ListDoctors();
            doctoresDisponibles = listaDoctores.listDoctors();

            comboMedicos.removeAllItems();

            for (Doctor doctor : doctoresDisponibles) {
                if (doctor.isActive()) {
                    comboMedicos.addItem(doctor.getFullName() + " - " + doctor.getSpecialty());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar médicos: " + e.getMessage());
        }
    }

    public ViewCreateAppointment() {
        initComponents();

        getContentPane().setBackground(new java.awt.Color(235, 225, 245));
        jPanel1.setBackground(new java.awt.Color(245, 238, 250));

        txtUUIDcita.setText(UUID.randomUUID().toString());
        txtUUIDcita.setEditable(false);

        cargarMedicos();

        setSize(430, 390);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUUIDcita = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInePaci = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        ButonCrrearCita = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtmotivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        comboMedicos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("UUID CITA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 10));
        jPanel1.add(txtUUIDcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 20));

        jLabel1.setText("Paciente (INE)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 124, 20));
        jPanel1.add(txtInePaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jLabel2.setText("UUID Medico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 110, 10));

        jLabel3.setText("Fecha yy-mm-dd");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, 110, 10));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, 140, 20));

        jlabel.setText("Hora");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, 110, 10));
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, 140, 20));

        ButonCrrearCita.setText("Crear");
        ButonCrrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonCrrearCitaActionPerformed(evt);
            }
        });
        jPanel1.add(ButonCrrearCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel5.setText("Motivo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, 40));
        jPanel1.add(txtmotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, 80));

        jLabel6.setText("Observaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, -1));
        jPanel1.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 160, 80));

        comboMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonCrrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonCrrearCitaActionPerformed
        // TODO add your handling code here:
        try {
            String id = txtUUIDcita.getText().trim();
            String ineTexto = txtInePaci.getText().trim();
            String fechaTexto = txtFecha.getText().trim();
            String horaTexto = txtHora.getText().trim();
            String motivo = txtmotivo.getText().trim();
            String observaciones = txtObservaciones.getText().trim();

            int indiceMedico = comboMedicos.getSelectedIndex();

            if (indiceMedico == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un médico.");
                return;
            }

            Doctor doctorSeleccionado = doctoresDisponibles.get(indiceMedico);
            String uuidMedico = doctorSeleccionado.getId();

            if (ineTexto.isEmpty() || fechaTexto.isEmpty() || horaTexto.isEmpty() || motivo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios.");
                return;
            }

            int inePaciente = Integer.parseInt(ineTexto);
            LocalDate fecha = LocalDate.parse(fechaTexto);
            LocalTime hora = LocalTime.parse(horaTexto);

            ListPatients listaPacientes = new ListPatients();
            ArrayList<Patient> pacientes = listaPacientes.listPatients();
            boolean pacienteExiste = false;

            for (Patient paciente : pacientes) {
                if (paciente.getIne() == inePaciente) {
                    pacienteExiste = true;
                    break;
                }
            }

            if (!pacienteExiste) {
                JOptionPane.showMessageDialog(this, "No existe ningún paciente con el INE: " + inePaciente);
                return;
            }

            ListAppointment listaCitas = new ListAppointment();
            ArrayList<Appointment> citas = listaCitas.listAppointments();

            for (Appointment cita : citas) {
                if (cita.getUUIdDoctor().equals(uuidMedico) && cita.getDate().equals(fecha) && cita.getStartHour().equals(hora) && !cita.isDeleted() && !cita.isStatus().equalsIgnoreCase("cancelada")) {
                    JOptionPane.showMessageDialog(this, "El médico ya tiene una cita programada para esa fecha y hora.");
                    return;
                }
            }

            Appointment appointment = new Appointment();
            appointment.setId(id);
            appointment.setInePaciente(inePaciente);
            appointment.setUUIdDoctor(uuidMedico);
            appointment.setDate(fecha);
            appointment.setStartHour(hora);
            appointment.setReason(motivo);
            appointment.setStatus("programada");
            appointment.setObservation(observaciones);
            appointment.setDeleted(false);

            CreateAppointment createAppointment = new CreateAppointment();
            createAppointment.createAppointment(appointment);

            JOptionPane.showMessageDialog(this, "Cita creada correctamente.");

            txtInePaci.setText("");
            txtFecha.setText("");
            txtHora.setText("");
            txtmotivo.setText("");
            txtObservaciones.setText("");
            comboMedicos.setSelectedIndex(-1);
            txtUUIDcita.setText(UUID.randomUUID().toString());

        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, "El INE debe ser un número válido.");
        } catch (java.time.format.DateTimeParseException exception) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener formato YYYY-MM-DD\ny la hora formato HH:mm.");
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Error al crear la cita: " + exception.getMessage());
        }
    }//GEN-LAST:event_ButonCrrearCitaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCreateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCreateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCreateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCreateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCreateAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonCrrearCita;
    private javax.swing.JComboBox<String> comboMedicos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtInePaci;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtUUIDcita;
    private javax.swing.JTextField txtmotivo;
    // End of variables declaration//GEN-END:variables
}
