/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.VistasDoctor;

import Vistas.General;
import com.mycompany.practicaunoarchivos.DoctorService.ChangeStatusDoctor;
import com.mycompany.practicaunoarchivos.DoctorService.ListDoctors;
import com.mycompany.practicaunoarchivos.DoctorService.SearchDoctor;
import com.mycompany.practicaunoarchivos.Models.Doctor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class GeneralDoctor extends javax.swing.JFrame {

    private void cargarDoctores() {

        ListDoctors listDoctors = new ListDoctors();

        ArrayList<Doctor> doctores = listDoctors.listDoctors();

        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        for (Doctor doctor : doctores) {

            modelo.addRow(new Object[]{
                doctor.getId(),
                doctor.getFullName(),
                doctor.getSpecialty(),
                doctor.getPhoneNumber(),
                doctor.getEmail(),
                doctor.getStartHour(),
                doctor.getEndHour(),
                doctor.isActive() ? "Activo" : "Inactivo"
            });
        }
    }

    private void cargarTabla(ArrayList<Doctor> doctores) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Doctor doctor : doctores) {
            modelo.addRow(new Object[]{
                doctor.getId(),
                doctor.getFullName(),
                doctor.getSpecialty(),
                doctor.getPhoneNumber(),
                doctor.getEmail(),
                doctor.getStartHour(),
                doctor.getEndHour(),
                doctor.isActive() ? "Activo" : "Inactivo"
            });
        }
    }

    private void cargarEspecialidades() {
        jComboBoxEspecialidad.removeAllItems();
        jComboBoxEspecialidad.addItem("Todas");

        ArrayList<String> especialidades = new ArrayList<>();

        for (Doctor doctor : new ListDoctors().listDoctors()) {
            if (!especialidades.contains(doctor.getSpecialty())) {
                especialidades.add(doctor.getSpecialty());
                jComboBoxEspecialidad.addItem(doctor.getSpecialty());
            }
        }
    }

    /**
     * Creates new form GeneralDoctor
     */
    public GeneralDoctor() {

        initComponents();

        cargarDoctores();
        cargarEspecialidades();

        getContentPane().setBackground(new Color(235, 225, 245));
        panelPrincipal.setBackground(new Color(245, 238, 250));

        jTable1.setRowHeight(28);

        jTable1.getTableHeader().setBackground(new Color(210, 190, 230));

        jTable1.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)
        );

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int fila = jTable1.getSelectedRow();

                if (fila != -1) {
                    txtSearch.setText(
                            jTable1.getValueAt(fila, 0).toString()
                    );
                }
            }
        });

        setTitle("Gestion de Medicos");
        setSize(700, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        buttonCreate = new javax.swing.JButton();
        jButtonDesactivar = new javax.swing.JButton();
        jButtonActivar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        cerrarbutton = new javax.swing.JButton();
        mostrarTodo = new javax.swing.JButton();
        BotonDesactivos = new javax.swing.JButton();
        todos = new javax.swing.JButton();
        botonActivos = new javax.swing.JButton();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        tablaDoctores = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpdate.setText("Actualizar ");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 367, 129, 41));

        buttonCreate.setText("Nuevo Medico");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });
        panelPrincipal.add(buttonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 367, 129, 41));

        jButtonDesactivar.setText("Desactivar");
        jButtonDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesactivarActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButtonDesactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 367, 129, 41));

        jButtonActivar.setText("Activar");
        jButtonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivarActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButtonActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 367, 129, 41));

        jTextField1.setText("BUSCAR");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        panelPrincipal.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 6, -1, 31));
        panelPrincipal.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 10, 251, -1));

        cerrarbutton.setText("Cerrar");
        cerrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarbuttonActionPerformed(evt);
            }
        });
        panelPrincipal.add(cerrarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 129, 41));

        mostrarTodo.setText("Mostrar Todo");
        mostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodoActionPerformed(evt);
            }
        });
        panelPrincipal.add(mostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        BotonDesactivos.setText("Desactivos");
        BotonDesactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDesactivosActionPerformed(evt);
            }
        });
        panelPrincipal.add(BotonDesactivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 90, 30));

        todos.setText("TODOS");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });
        panelPrincipal.add(todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));

        botonActivos.setText("Activos");
        botonActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActivosActionPerformed(evt);
            }
        });
        panelPrincipal.add(botonActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 90, 30));

        jComboBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialidadActionPerformed(evt);
            }
        });
        panelPrincipal.add(jComboBoxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UUID", "Nombre", "Especialidad", "Telefono", "Email", "Hora  Inicio", "Hora fin", "Estado"
            }
        ));
        tablaDoctores.setViewportView(jTable1);

        panelPrincipal.add(tablaDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 640, 220));

        add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 700, 414));
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        // TODO add your handling code here:
        ViewCreateDoctor viewdc = new ViewCreateDoctor();
        viewdc.setVisible(true);
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        ViewUpdateDoctor updatedc = new ViewUpdateDoctor();
        updatedc.setVisible(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        String buscar = txtSearch.getText().trim();

        if (buscar.isEmpty()) {
            cargarTabla(new ListDoctors().listDoctors());
            return;
        }

        SearchDoctor searchDoctor = new SearchDoctor();
        ArrayList<Doctor> resultados = searchDoctor.searchDoctor(buscar);

        cargarTabla(resultados);

        if (resultados.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontraron medicos.");
        }

    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void cerrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarbuttonActionPerformed
        // TODO add your handling code here:
        General vista = new General();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarbuttonActionPerformed

    private void mostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodoActionPerformed
        // TODO add your handling code here:
        cargarTabla(new ListDoctors().listDoctors());
    }//GEN-LAST:event_mostrarTodoActionPerformed

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        // TODO add your handling code here:
        cargarTabla(new ListDoctors().listDoctors());
    }//GEN-LAST:event_todosActionPerformed

    private void botonActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActivosActionPerformed
        // TODO add your handling code here:
        ArrayList<Doctor> activos = new ArrayList<>();

        for (Doctor doctor : new ListDoctors().listDoctors()) {
            if (doctor.isActive()) {
                activos.add(doctor);
            }
        }

        cargarTabla(activos);
    }//GEN-LAST:event_botonActivosActionPerformed

    private void BotonDesactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDesactivosActionPerformed
        // TODO add your handling code here:
        ArrayList<Doctor> inactivos = new ArrayList<>();

        for (Doctor doctor : new ListDoctors().listDoctors()) {
            if (!doctor.isActive()) {
                inactivos.add(doctor);
            }
        }

        cargarTabla(inactivos);
    }//GEN-LAST:event_BotonDesactivosActionPerformed

    private void jComboBoxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadActionPerformed
        // TODO add your handling code here:
        if (jComboBoxEspecialidad.getSelectedItem() == null) {
            return;
        }

        String especialidad = jComboBoxEspecialidad.getSelectedItem().toString();

        if (especialidad.equals("Todas")) {
            cargarTabla(new ListDoctors().listDoctors());
            return;
        }

        ArrayList<Doctor> resultados = new ArrayList<>();

        for (Doctor doctor : new ListDoctors().listDoctors()) {
            if (doctor.getSpecialty().equalsIgnoreCase(especialidad)) {
                resultados.add(doctor);
            }
        }

        cargarTabla(resultados);

    }//GEN-LAST:event_jComboBoxEspecialidadActionPerformed

    private void jButtonDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesactivarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un medico de la tabla.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        ChangeStatusDoctor changeStatus = new ChangeStatusDoctor();

        if (changeStatus.changeStatus(id, false)) {

            JOptionPane.showMessageDialog(this,
                    "Medico desactivado correctamente.");

            cargarDoctores();

        } else {

            JOptionPane.showMessageDialog(this,
                    "No se encontro el medico.");
        }
    }//GEN-LAST:event_jButtonDesactivarActionPerformed

    private void jButtonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un medico de la tabla.");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        ChangeStatusDoctor changeStatus = new ChangeStatusDoctor();

        if (changeStatus.changeStatus(id, true)) {

            JOptionPane.showMessageDialog(this,
                    "Medico activado correctamente.");

            cargarDoctores();

        } else {

            JOptionPane.showMessageDialog(this,
                    "No se encontro el medico.");
        }
    }//GEN-LAST:event_jButtonActivarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralDoctor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonDesactivos;
    private javax.swing.JButton botonActivos;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton cerrarbutton;
    private javax.swing.JButton jButtonActivar;
    private javax.swing.JButton jButtonDesactivar;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxEspecialidad;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mostrarTodo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane tablaDoctores;
    private javax.swing.JButton todos;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
