/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.VistasDoctor;

import com.mycompany.practicaunoarchivos.DoctorService.CreateDoctor;
import com.mycompany.practicaunoarchivos.Models.Doctor;
import java.awt.Color;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class ViewCreateDoctor extends javax.swing.JFrame {

    /**
     * Creates new form CreateDoctor
     */
    public ViewCreateDoctor() {
        initComponents();

        getContentPane().setBackground(new Color(235, 225, 245));

        setTitle("Registrar Medico");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSpecialty = new javax.swing.JLabel();
        txtSpecialty = new javax.swing.JTextField();
        lbFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblStartHour = new javax.swing.JLabel();
        txtStartHour = new javax.swing.JTextField();
        lblEndHour = new javax.swing.JLabel();
        txtEndHour = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpecialty.setText("Especialidad");
        jPanel1.add(lblSpecialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 196, -1));

        txtSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtSpecialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 301, -1));

        lbFullName.setText("Nombre y Apellido ( obligatorio)");
        jPanel1.add(lbFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 196, -1));

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 301, -1));

        lblPhone.setText("Telefono");
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 196, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 301, -1));

        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 196, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 301, -1));

        lblStartHour.setText("Hora de Inicio");
        jPanel1.add(lblStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 196, -1));

        txtStartHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartHourActionPerformed(evt);
            }
        });
        jPanel1.add(txtStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 301, -1));

        lblEndHour.setText("Hora de finalizacion");
        jPanel1.add(lblEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 196, -1));

        txtEndHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndHourActionPerformed(evt);
            }
        });
        jPanel1.add(txtEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 301, -1));

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("UUID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 190, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 0, 1090, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialtyActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtStartHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartHourActionPerformed

    private void txtEndHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndHourActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String fullName = txtFullName.getText();
        String specialty = txtSpecialty.getText();
        String phoneNumber = txtPhone.getText();
        String email = txtEmail.getText();

        if (fullName.isEmpty() || specialty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los nombres y la especialidad son obligatorios.");
            return;
        }

        try {
            LocalTime startHour = LocalTime.parse(txtStartHour.getText());
            LocalTime endHour = LocalTime.parse(txtEndHour.getText());

            Doctor doctor = new Doctor(fullName, specialty, phoneNumber, email, startHour, endHour);

            CreateDoctor createDoctor = new CreateDoctor();
            createDoctor.createDoctor(doctor);
            txtId.setText(doctor.getId());

            JOptionPane.showMessageDialog(this, "Doctor guardado correctamente.");

            txtFullName.setText("");
            txtSpecialty.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtStartHour.setText("");
            txtEndHour.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El horario debe tener formato HH:mm.");
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GeneralDoctor vista = new GeneralDoctor();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         GeneralDoctor vista = new GeneralDoctor();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCreateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCreateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndHour;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblStartHour;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndHour;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpecialty;
    private javax.swing.JTextField txtStartHour;
    // End of variables declaration//GEN-END:variables
}
