/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.VistasDoctor;

import com.mycompany.practicaunoarchivos.DoctorService.SearchDoctor;
import com.mycompany.practicaunoarchivos.DoctorService.UpdateDoctor;
import com.mycompany.practicaunoarchivos.Models.Doctor;
import java.awt.Color;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class ViewUpdateDoctor extends javax.swing.JFrame {

    /**
     * Creates new form ViewUpdateDoctor
     */
    public ViewUpdateDoctor() {
        initComponents();

        getContentPane().setBackground(new Color(235, 225, 245));

        setTitle("Actualizar Medico");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDoc = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSpecialty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStartHour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEndHour = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdateDoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        UpdateDoc.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("UUID");
        UpdateDoc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, -1));

        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE Y APELLIDO");
        UpdateDoc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        txtSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialtyActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtSpecialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ESPECIALIDAD");
        UpdateDoc.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TELEFONO");
        UpdateDoc.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("EMAIL");
        UpdateDoc.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 190, -1));

        txtStartHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartHourActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("HORA INICIO");
        UpdateDoc.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 190, -1));

        txtEndHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndHourActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("HORA FIN");
        UpdateDoc.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, -1));

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        UpdateDoc.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 130, 50));

        txtBuscar.setText("BUSCAR");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 130, 50));

        jButton3.setText("GUARDAR CAMBIOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        UpdateDoc.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 50));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        UpdateDoc.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("BUSCAR");
        UpdateDoc.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 190, -1));

        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        UpdateDoc.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpdateDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialtyActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtStartHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartHourActionPerformed

    private void txtEndHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndHourActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String fullName = txtFullName.getText();
        String specialty = txtSpecialty.getText();
        String phoneNumber = txtPhone.getText();
        String email = txtEmail.getText();

        if (id.isEmpty() || fullName.isEmpty() || specialty.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "UUID, nombre y especialidad son obligatorios.");
            return;
        }

        try {
            LocalTime startHour = LocalTime.parse(txtStartHour.getText());
            LocalTime endHour = LocalTime.parse(txtEndHour.getText());

            Doctor doctor = new Doctor();

            doctor.setId(id);
            doctor.setFullName(fullName);
            doctor.setSpecialty(specialty);
            doctor.setPhoneNumber(phoneNumber);
            doctor.setEmail(email);
            doctor.setStartHour(startHour);
            doctor.setEndHour(endHour);

            UpdateDoctor actualizar = new UpdateDoctor();

            boolean resultado = actualizar.updateDoctor(doctor);

            if (resultado) {
                JOptionPane.showMessageDialog(this,
                        "Doctor actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontro el doctor.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Las horas deben tener formato HH:mm.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        String buscar = txtSearch.getText();

        SearchDoctor searchDoctor = new SearchDoctor();

        ArrayList<Doctor> resultados = searchDoctor.searchDoctor(buscar);

        System.out.println("Buscando: [" + buscar + "]");
        System.out.println("Resultados: " + resultados.size());

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Doctor no encontrado.");
            return;
        }

        Doctor doctor = resultados.get(0);

        txtId.setText(doctor.getId());
        txtFullName.setText(doctor.getFullName());
        txtSpecialty.setText(doctor.getSpecialty());
        txtPhone.setText(doctor.getPhoneNumber());
        txtEmail.setText(doctor.getEmail());
        txtStartHour.setText(doctor.getStartHour().toString());
        txtEndHour.setText(doctor.getEndHour().toString());
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GeneralDoctor vista = new GeneralDoctor();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GeneralDoctor vista = new GeneralDoctor();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GeneralDoctor vista = new GeneralDoctor();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton txtBuscar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndHour;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpecialty;
    private javax.swing.JTextField txtStartHour;
    // End of variables declaration//GEN-END:variables
}
